version: '3.8'

services:
  barber-shop-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barber-shop-ui
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - barber-shop-network

networks:
  barber-shop-network:
    external: true
